#!/usr/bin/env bash

#
# Author: Mysall
#

# Font for all text
FONT1="-lucy-tewi-medium-r-normal--11-90-100-100-c-60-ISO10646-1"

# Icon fon
FONT2="-wuncon-siji-medium-r-normal--10-100-75-75-C-80-ISO10646-1"

# Bar size
SIZE="1920x20"

# Size of the underline
ULINE="1"

# Timeout
TIMEOUT=0.5

# Background color
BG="#1d1f21"

# Foreground color
FG="#c5c8c6"

# Icon background color
#IB="#316b59"
IB="#111213"

# First desktop icon (Computer)
fdi="\ue1d7"

# Second desktop icon (Code)
sdi="\ue00a"

# Third desktop icon (Code)
tdi="\ue1ef"

# Last desktop icon (Folder)
ldi="\ue1e0"

# Mail desktop icon (Mail)
mdi="\ue229"

# The icon for the date
ci="\ue266"

# Temperature icon
cpui="\ue0ce"

# Volume mute icon
vmi="\ue04f"

# Volume icon
vi="\ue05d"

# Time icon
ti="\ue0a3"
# Start the bar script

function bar {
    
    # Show an icon which relates to the current desktop
    function desktop {
        # Find the current desktop (0 index)
        CURRENT=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}')

        case $CURRENT in
            # First
            0) echo -e %{B$IB}%{F$FG} $fdi %{B$BG}%{F$FG} $sdi %{B$BG}%{F$FG} $tdi %{B$BG}%{F$FG} $ldi %{B$BG}%{F$FG} $mdi %{F-};;
            1) echo -e %{B$BG}%{F$FG} $fdi %{B$IB}%{F$FG} $sdi %{B$BG}%{F$FG} $tdi %{B$BG}%{F$FG} $ldi %{B$BG}%{F$FG} $mdi %{F-};;
            2) echo -e %{B$BG}%{F$FG} $fdi %{B$BG}%{F$FG} $sdi %{B$IB}%{F$FG} $tdi %{B$BG}%{F$FG} $ldi %{B$BG}%{F$FG} $mdi %{F-};;
            3) echo -e %{B$BG}%{F$FG} $fdi %{B$BG}%{F$FG} $sdi %{B$BG}%{F$FG} $tdi %{B$IB}%{F$FG} $ldi %{B$BG}%{F$FG} $mdi %{F-};;
            4) echo -e %{B$BG}%{F$FG} $fdi %{B$BG}%{F$FG} $sdi %{B$BG}%{F$FG} $tdi %{B$BG}%{F$FG} $ldi %{B$IB}%{F$FG} $mdi %{F-} 
        esac
    }

    # Show the date
    function timedisplay {
        DATE=$(date "+%A %b %d %Y")
        echo -e %{B$IB}%{F$FG} $ci %{B$BG}%{F$FG} $DATE %{F-}
    }

    # Show the cpu temperature
    function cpuTemp {
        TEMP=$(sensors | grep "Physical id 0" | cut -d'+' -f2 | head -c2) 
        echo -e %{B$IB}%{F$FG} $cpui %{B$BG}%{F$FG} $TEMP %{F-}
    }

    # Show the time
    function volume {
        VOL_PERC=$(amixer get Master | grep '%' | awk '{gsub(/[\[\]%]/,""); print $4}')
        VOL_STAT=$(amixer get Master | grep '%' | awk '{gsub(/[\[\]]/,""); print $6}')

        # Check if the volume is muted
        if [ $VOL_STAT == "on" ]; 
        then
            echo -e %{B$IB}%{F$FG} $vi %{B$BG}%{F$FG} $VOL_PERC% %{F-}
        else
            echo -e %{B$IB}%{F$FG} $vmi %{B$BG}%{F$FG} Mute %{F-}
        fi 

    }

    # Show the time
    function currentTime {
        TIME=$(date "+%H:%M:%S")
        echo -e %{B$IB}%{F$FG} $ti %{B$BG}%{F$FG} $TIME %{F-}
    }

    echo "%{l}$(desktop)%{c}$(timedisplay)%{r}$(cpuTemp)$(volume)$(currentTime)"
}

while :; do
    echo $(bar)
    sleep $TIMEOUT
done | lemonbar -g $SIZE -u $ULINE -f $FONT2 -f $FONT1 -B $BG
